// Generated by CoffeeScript 1.10.0
(function() {
  var greet, sum;

  sum = function(sum1, sum2) {
    return "Las suma de los numeros es " + (sum1 + sum2);
  };

  greet = function(name) {
    if (name == null) {
      name = 'Stranger';
    }
    return "Hi " + name + ", what are you doing here?";
  };

}).call(this);
